### ISSUE TITLE
SIMSUN_Benchmark_Char: No such file or directory

### ISSUE THREAD

**Issue by usernononoloser** [FudanVI/FudanOCR#104]
我无法利用VCTR_test数据集进行模型训练，

Traceback (most recent call last):
  File "train.py", line 15, in <module>
    char2img_dict, char2rotimg_dict = get_sample()
  File "/home/wangshicheng/Project/FudanOCR-main/orientation-independent-CTR/util.py", line 95, in get_sample
    dataset = lmdbDataset(dataset_root)
  File "/home/wangshicheng/Project/FudanOCR-main/orientation-independent-CTR/data/lmdbReader.py", line 19, in __init__
    meminit=False)
lmdb.Error: /home/wangshicheng/Project/FudanOCR-main/orientation-independent-CTR/SIMSUN_Benchmark_Char: No such file or directory

**Comment by ChrisEvans2** [comment]
他是用scene Text来训练的吧
