### ISSUE TITLE
lmdb can not find my file.

### ISSUE THREAD

**Issue by zhouyupeng973** [FudanVI/FudanOCR#90]
./data/doc

Traceback (most recent call last):
  File "train.py", line 36, in <module>
    train_loader, test_loader = get_data_package()
  File "/home/libj/ZYP/image-ids-CTR/util.py", line 56, in get_data_package
    _ , dataset = get_dataloader(dataset_root,shuffle=True)
  File "/home/libj/ZYP/image-ids-CTR/util.py", line 36, in get_dataloader
    dataset = lmdbDataset(root,resizeNormalize((config['imageW'],config['imageH'])))
  File "/home/libj/ZYP/image-ids-CTR/data/lmdbReader.py", line 21, in __init__
    meminit=False)
lmdb.Error: : No such file or directory

**Comment by ningyuv** [comment]
check first: your lmdb dataset should contains a `data.mdb` and a `lock.mdb` in your path `./data/doc`

**Comment by zhouyupeng973** [comment]
> check first: your lmdb dataset should contains a `data.mdb` and a `lock.mdb` in your path `./data/doc`

It did have.
