### ISSUE TITLE
字典里面的字符是不是不够啊？除了没有逗号，有时候会出现字典里没有这个汉字。

### ISSUE THREAD

**Issue by zhouyupeng973** [FudanVI/FudanOCR#93]
-------------
training: 735
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
文在城关经营旅店和木匠铺二十多年,有房屋四十$
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    length, text_input, text_gt, string_label = converter(label)
  File "/home/libj/ZYP/image-ids-CTR/util.py", line 118, in converter
    text_input[i][j + 1] = alp2num[label[i][j]]
KeyError: ','
(transformer) libj@cqupt:~/ZYP/image-ids-CTR$

**Comment by Skywalker-Harrison** [comment]
同问

**Comment by zhouyupeng973** [comment]
> 同问

你好，请问你解决字典的问题了吗？

**Comment by Skywalker-Harrison** [comment]
I think we need to add punctuation to the dictionary, otherwise it will be replaced by placeholders, in my case, it is replaced by "START"

**Comment by TheLei** [comment]
同问，您解决了这个问题吗

**Comment by Tom98714** [comment]
> training: 735 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ 文在城关经营旅店和木匠铺二十多年,有房屋四十$ Traceback (most recent call last): File "train.py", line 215, in length, text_input, text_gt, string_label = converter(label) File "/home/libj/ZYP/image-ids-CTR/util.py", line 118, in converter text_input[i][j + 1] = alp2num[label[i][j]] KeyError: ',' (transformer) libj@cqupt:~/ZYP/image-ids-CTR$

你好，请问你的这个问题解决了吗，我也遇到这个问题了
